// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#include <QColor>
#include <QFont>
#include <QImage>
#include <QString>
#include <QVector>

class ContactSheetComposer
{
public:
    static QVector<double> makeEvenTimes(
        double durationSeconds,
        int count,
        double startMarginPercent = 7.0,
        double endMarginPercent = 7.0,
        bool randomizePositions = false,
        double randomizePercent = 10.0,
        bool useSpecificTimestep = false,
        double timestepSeconds = 60.0
    );

    static QImage compose(
        const QVector<QImage> &frames,
        const QVector<double> &times,
        int columns,
        int rows,
        int thumbWidth,
        int gap,
        const QString &title,
        const QString &headerInfo,
        bool drawTimestamps,
        const QFont &textFont,
        bool drawInfoText = true,
        const QString &infoTextPosition = "upper-left",
        const QString &timestampPosition = "lower-left",
        bool drawAdditionalTitle = true,
        const QString &additionalTitle = "Generated by Thumbnail me",
        const QColor &backgroundColor = QColor(20, 20, 20),
        const QColor &titleTextColor = QColor(255, 255, 255),
        const QColor &infoTextColor = QColor(230, 230, 230),
        const QColor &countTextColor = QColor(210, 210, 210),
        const QColor &timestampTextColor = QColor(255, 255, 255),
        const QColor &timestampBackgroundColor = QColor(0, 0, 0, 170),
        bool drawTileBorder = true,
        const QColor &tileBorderColor = QColor(70, 70, 70)
    );
};
